/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */
#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CMsgGCCStrike15_v2_Party_Search, CMsgGCCStrike15_v2_Party_Search, AUTO)


PB_BIND(CMsgGCCStrike15_v2_Party_SearchResults, CMsgGCCStrike15_v2_Party_SearchResults, AUTO)


PB_BIND(CMsgGCCStrike15_v2_Party_SearchResults_Entry, CMsgGCCStrike15_v2_Party_SearchResults_Entry, AUTO)


PB_BIND(CMsgGCCStrike15_v2_Party_Invite, CMsgGCCStrike15_v2_Party_Invite, AUTO)


PB_BIND(DetailedSearchStatistic, DetailedSearchStatistic, AUTO)


PB_BIND(GlobalStatistics, GlobalStatistics, AUTO)


PB_BIND(IpAddressMask, IpAddressMask, AUTO)


PB_BIND(CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate, CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate, 2)


PB_BIND(CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note, CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note, AUTO)




