/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ECsgoGCMsg { 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Base = 9100, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchmakingStart = 9101, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchmakingStop = 9102, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchmakingClient2ServerPing = 9103, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate = 9104, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchmakingServerReservationResponse = 9106, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchmakingGC2ClientReserve = 9107, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchmakingClient2GCHello = 9109, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchmakingGC2ClientHello = 9110, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchmakingGC2ClientAbandon = 9112, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchmakingGCOperationalStats = 9115, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchmakingOperator2GCBlogUpdate = 9117, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ServerNotificationForUserPenalty = 9118, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientReportPlayer = 9119, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientReportServer = 9120, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientCommendPlayer = 9121, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientReportResponse = 9122, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientCommendPlayerQuery = 9123, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientCommendPlayerQueryResponse = 9124, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_WatchInfoUsers = 9126, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientRequestPlayersProfile = 9127, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_PlayersProfile = 9128, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_PlayerOverwatchCaseUpdate = 9131, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_PlayerOverwatchCaseAssignment = 9132, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_PlayerOverwatchCaseStatus = 9133, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GC2ClientTextMsg = 9134, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Client2GCTextMsg = 9135, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchEndRunRewardDrops = 9136, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchEndRewardDropsNotification = 9137, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientRequestWatchInfoFriends2 = 9138, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchList = 9139, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchListRequestCurrentLiveGames = 9140, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchListRequestRecentUserGames = 9141, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GC2ServerReservationUpdate = 9142, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientVarValueNotificationInfo = 9144, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchListRequestTournamentGames = 9146, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchListRequestFullGameInfo = 9147, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GiftsLeaderboardRequest = 9148, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GiftsLeaderboardResponse = 9149, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ServerVarValueNotificationInfo = 9150, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientSubmitSurveyVote = 9152, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Server2GCClientValidate = 9153, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchListRequestLiveGameForUser = 9154, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Client2GCEconPreviewDataBlockRequest = 9156, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Client2GCEconPreviewDataBlockResponse = 9157, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_AccountPrivacySettings = 9158, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_SetMyActivityInfo = 9159, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchListRequestTournamentPredictions = 9160, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_MatchListUploadTournamentPredictions = 9161, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_DraftSummary = 9162, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientRequestJoinFriendData = 9163, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientRequestJoinServerData = 9164, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientRequestNewMission = 9165, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GC2ClientTournamentInfo = 9167, 
    ECsgoGCMsg_k_EMsgGC_GlobalGame_Subscribe = 9168, 
    ECsgoGCMsg_k_EMsgGC_GlobalGame_Unsubscribe = 9169, 
    ECsgoGCMsg_k_EMsgGC_GlobalGame_Play = 9170, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_AcknowledgePenalty = 9171, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Client2GCRequestPrestigeCoin = 9172, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GC2ClientGlobalStats = 9173, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Client2GCStreamUnlock = 9174, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_FantasyRequestClientData = 9175, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_FantasyUpdateClientData = 9176, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GCToClientSteamdatagramTicket = 9177, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientToGCRequestTicket = 9178, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientToGCRequestElevate = 9179, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GlobalChat = 9180, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GlobalChat_Subscribe = 9181, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GlobalChat_Unsubscribe = 9182, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientAuthKeyCode = 9183, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GotvSyncPacket = 9184, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientPlayerDecalSign = 9185, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientLogonFatalError = 9187, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientPollState = 9188, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Party_Register = 9189, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Party_Unregister = 9190, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Party_Search = 9191, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Party_Invite = 9192, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_Account_RequestCoPlays = 9193, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientGCRankUpdate = 9194, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientRequestOffers = 9195, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientAccountBalance = 9196, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientPartyJoinRelay = 9197, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientPartyWarning = 9198, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_SetEventFavorite = 9200, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GetEventFavorites_Request = 9201, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientPerfReport = 9202, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GetEventFavorites_Response = 9203, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientRequestSouvenir = 9204, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientReportValidation = 9205, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GC2ClientRefuseSecureMode = 9206, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_GC2ClientRequestValidation = 9207, 
    ECsgoGCMsg_k_EMsgGCCStrike15_v2_ClientRedeemMissionReward = 9209, 
    ECsgoGCMsg_k_EMsgGCCStrike15_ClientDeepStats = 9210, 
    ECsgoGCMsg_k_EMsgGCCStrike15_StartAgreementSessionInGame = 9211 
} ECsgoGCMsg;

/* Struct definitions */
typedef struct _CMsgGCCStrike15_v2_Party_SearchResults { 
    pb_callback_t entries; 
} CMsgGCCStrike15_v2_Party_SearchResults;

typedef struct _CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note { 
    bool has_type;
    int32_t type; 
    bool has_region_id;
    int32_t region_id; 
    bool has_region_r;
    float region_r; 
    bool has_distance;
    float distance; 
} CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note;

typedef struct _CMsgGCCStrike15_v2_Party_Invite { 
    bool has_accountid;
    uint32_t accountid; 
    bool has_lobbyid;
    uint32_t lobbyid; 
} CMsgGCCStrike15_v2_Party_Invite;

typedef struct _CMsgGCCStrike15_v2_Party_Search { 
    bool has_ver;
    uint32_t ver; 
    bool has_apr;
    uint32_t apr; 
    bool has_ark;
    uint32_t ark; 
    pb_callback_t grps; 
    bool has_launcher;
    uint32_t launcher; 
    bool has_game_type;
    uint32_t game_type; 
} CMsgGCCStrike15_v2_Party_Search;

typedef struct _CMsgGCCStrike15_v2_Party_SearchResults_Entry { 
    bool has_id;
    uint32_t id; 
    bool has_grp;
    uint32_t grp; 
    bool has_game_type;
    uint32_t game_type; 
    bool has_apr;
    uint32_t apr; 
    bool has_ark;
    uint32_t ark; 
    bool has_loc;
    uint32_t loc; 
} CMsgGCCStrike15_v2_Party_SearchResults_Entry;

typedef struct _DetailedSearchStatistic { 
    bool has_game_type;
    uint32_t game_type; 
    bool has_search_time_avg;
    uint32_t search_time_avg; 
    bool has_players_searching;
    uint32_t players_searching; 
} DetailedSearchStatistic;

typedef struct _GlobalStatistics { 
    bool has_players_online;
    uint32_t players_online; 
    bool has_servers_online;
    uint32_t servers_online; 
    bool has_players_searching;
    uint32_t players_searching; 
    bool has_servers_available;
    uint32_t servers_available; 
    bool has_ongoing_matches;
    uint32_t ongoing_matches; 
    bool has_search_time_avg;
    uint32_t search_time_avg; 
    pb_callback_t search_statistics; 
    pb_callback_t main_post_url; 
    bool has_required_appid_version;
    uint32_t required_appid_version; 
    bool has_pricesheet_version;
    uint32_t pricesheet_version; 
    bool has_twitch_streams_version;
    uint32_t twitch_streams_version; 
    bool has_active_tournament_eventid;
    uint32_t active_tournament_eventid; 
    bool has_active_survey_id;
    uint32_t active_survey_id; 
    bool has_rtime32_cur;
    uint32_t rtime32_cur; 
    bool has_rtime32_event_start;
    uint32_t rtime32_event_start; 
} GlobalStatistics;

typedef struct _IpAddressMask { 
    bool has_a;
    uint32_t a; 
    bool has_b;
    uint32_t b; 
    bool has_c;
    uint32_t c; 
    bool has_d;
    uint32_t d; 
    bool has_bits;
    uint32_t bits; 
    bool has_token;
    uint32_t token; 
} IpAddressMask;

typedef struct _CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate { 
    bool has_matchmaking;
    int32_t matchmaking; 
    pb_callback_t waiting_account_id_sessions; 
    pb_callback_t error; 
    pb_callback_t ongoingmatch_account_id_sessions; 
    bool has_global_stats;
    GlobalStatistics global_stats; 
    pb_callback_t failping_account_id_sessions; 
    pb_callback_t penalty_account_id_sessions; 
    pb_callback_t failready_account_id_sessions; 
    pb_callback_t vacbanned_account_id_sessions; 
    bool has_server_ipaddress_mask;
    IpAddressMask server_ipaddress_mask; 
    pb_callback_t notes; 
    pb_callback_t penalty_account_id_sessions_green; 
    pb_callback_t insufficientlevel_sessions; 
    pb_callback_t vsncheck_account_id_sessions; 
    pb_callback_t launcher_mismatch_sessions; 
    pb_callback_t insecure_account_id_sessions; 
} CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate;


/* Helper constants for enums */
#define _ECsgoGCMsg_MIN ECsgoGCMsg_k_EMsgGCCStrike15_v2_Base
#define _ECsgoGCMsg_MAX ECsgoGCMsg_k_EMsgGCCStrike15_StartAgreementSessionInGame
#define _ECsgoGCMsg_ARRAYSIZE ((ECsgoGCMsg)(ECsgoGCMsg_k_EMsgGCCStrike15_StartAgreementSessionInGame+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CMsgGCCStrike15_v2_Party_Search_init_default {false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0}
#define CMsgGCCStrike15_v2_Party_SearchResults_init_default {{{NULL}, NULL}}
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define CMsgGCCStrike15_v2_Party_Invite_init_default {false, 0, false, 0}
#define DetailedSearchStatistic_init_default     {false, 0, false, 0, false, 0}
#define GlobalStatistics_init_default            {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define IpAddressMask_init_default               {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_init_default {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, GlobalStatistics_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, IpAddressMask_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_init_default {false, 0, false, 0, false, 0, false, 0}
#define CMsgGCCStrike15_v2_Party_Search_init_zero {false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0}
#define CMsgGCCStrike15_v2_Party_SearchResults_init_zero {{{NULL}, NULL}}
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define CMsgGCCStrike15_v2_Party_Invite_init_zero {false, 0, false, 0}
#define DetailedSearchStatistic_init_zero        {false, 0, false, 0, false, 0}
#define GlobalStatistics_init_zero               {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define IpAddressMask_init_zero                  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_init_zero {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, GlobalStatistics_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, IpAddressMask_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_init_zero {false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define CMsgGCCStrike15_v2_Party_SearchResults_entries_tag 1
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_type_tag 1
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_region_id_tag 2
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_region_r_tag 3
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_distance_tag 4
#define CMsgGCCStrike15_v2_Party_Invite_accountid_tag 1
#define CMsgGCCStrike15_v2_Party_Invite_lobbyid_tag 2
#define CMsgGCCStrike15_v2_Party_Search_ver_tag  1
#define CMsgGCCStrike15_v2_Party_Search_apr_tag  2
#define CMsgGCCStrike15_v2_Party_Search_ark_tag  3
#define CMsgGCCStrike15_v2_Party_Search_grps_tag 4
#define CMsgGCCStrike15_v2_Party_Search_launcher_tag 5
#define CMsgGCCStrike15_v2_Party_Search_game_type_tag 6
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_id_tag 1
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_grp_tag 2
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_game_type_tag 3
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_apr_tag 4
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_ark_tag 5
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_loc_tag 6
#define DetailedSearchStatistic_game_type_tag    1
#define DetailedSearchStatistic_search_time_avg_tag 2
#define DetailedSearchStatistic_players_searching_tag 4
#define GlobalStatistics_players_online_tag      1
#define GlobalStatistics_servers_online_tag      2
#define GlobalStatistics_players_searching_tag   3
#define GlobalStatistics_servers_available_tag   4
#define GlobalStatistics_ongoing_matches_tag     5
#define GlobalStatistics_search_time_avg_tag     6
#define GlobalStatistics_search_statistics_tag   7
#define GlobalStatistics_main_post_url_tag       8
#define GlobalStatistics_required_appid_version_tag 9
#define GlobalStatistics_pricesheet_version_tag  10
#define GlobalStatistics_twitch_streams_version_tag 11
#define GlobalStatistics_active_tournament_eventid_tag 12
#define GlobalStatistics_active_survey_id_tag    13
#define GlobalStatistics_rtime32_cur_tag         14
#define GlobalStatistics_rtime32_event_start_tag 15
#define IpAddressMask_a_tag                      1
#define IpAddressMask_b_tag                      2
#define IpAddressMask_c_tag                      3
#define IpAddressMask_d_tag                      4
#define IpAddressMask_bits_tag                   5
#define IpAddressMask_token_tag                  6
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_matchmaking_tag 1
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_waiting_account_id_sessions_tag 2
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_error_tag 3
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_ongoingmatch_account_id_sessions_tag 6
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_global_stats_tag 7
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_failping_account_id_sessions_tag 8
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_penalty_account_id_sessions_tag 9
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_failready_account_id_sessions_tag 10
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_vacbanned_account_id_sessions_tag 11
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_server_ipaddress_mask_tag 12
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_notes_tag 13
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_penalty_account_id_sessions_green_tag 14
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_insufficientlevel_sessions_tag 15
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_vsncheck_account_id_sessions_tag 16
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_launcher_mismatch_sessions_tag 17
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_insecure_account_id_sessions_tag 18

/* Struct field encoding specification for nanopb */
#define CMsgGCCStrike15_v2_Party_Search_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   ver,               1) \
X(a, STATIC,   OPTIONAL, UINT32,   apr,               2) \
X(a, STATIC,   OPTIONAL, UINT32,   ark,               3) \
X(a, CALLBACK, REPEATED, UINT32,   grps,              4) \
X(a, STATIC,   OPTIONAL, UINT32,   launcher,          5) \
X(a, STATIC,   OPTIONAL, UINT32,   game_type,         6)
#define CMsgGCCStrike15_v2_Party_Search_CALLBACK pb_default_field_callback
#define CMsgGCCStrike15_v2_Party_Search_DEFAULT NULL

#define CMsgGCCStrike15_v2_Party_SearchResults_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           1)
#define CMsgGCCStrike15_v2_Party_SearchResults_CALLBACK pb_default_field_callback
#define CMsgGCCStrike15_v2_Party_SearchResults_DEFAULT NULL
#define CMsgGCCStrike15_v2_Party_SearchResults_entries_MSGTYPE CMsgGCCStrike15_v2_Party_SearchResults_Entry

#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, UINT32,   grp,               2) \
X(a, STATIC,   OPTIONAL, UINT32,   game_type,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   apr,               4) \
X(a, STATIC,   OPTIONAL, UINT32,   ark,               5) \
X(a, STATIC,   OPTIONAL, UINT32,   loc,               6)
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_CALLBACK NULL
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_DEFAULT NULL

#define CMsgGCCStrike15_v2_Party_Invite_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   accountid,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   lobbyid,           2)
#define CMsgGCCStrike15_v2_Party_Invite_CALLBACK NULL
#define CMsgGCCStrike15_v2_Party_Invite_DEFAULT NULL

#define DetailedSearchStatistic_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   game_type,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   search_time_avg,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   players_searching,   4)
#define DetailedSearchStatistic_CALLBACK NULL
#define DetailedSearchStatistic_DEFAULT NULL

#define GlobalStatistics_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   players_online,    1) \
X(a, STATIC,   OPTIONAL, UINT32,   servers_online,    2) \
X(a, STATIC,   OPTIONAL, UINT32,   players_searching,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   servers_available,   4) \
X(a, STATIC,   OPTIONAL, UINT32,   ongoing_matches,   5) \
X(a, STATIC,   OPTIONAL, UINT32,   search_time_avg,   6) \
X(a, CALLBACK, REPEATED, MESSAGE,  search_statistics,   7) \
X(a, CALLBACK, OPTIONAL, STRING,   main_post_url,     8) \
X(a, STATIC,   OPTIONAL, UINT32,   required_appid_version,   9) \
X(a, STATIC,   OPTIONAL, UINT32,   pricesheet_version,  10) \
X(a, STATIC,   OPTIONAL, UINT32,   twitch_streams_version,  11) \
X(a, STATIC,   OPTIONAL, UINT32,   active_tournament_eventid,  12) \
X(a, STATIC,   OPTIONAL, UINT32,   active_survey_id,  13) \
X(a, STATIC,   OPTIONAL, UINT32,   rtime32_cur,      14) \
X(a, STATIC,   OPTIONAL, UINT32,   rtime32_event_start,  15)
#define GlobalStatistics_CALLBACK pb_default_field_callback
#define GlobalStatistics_DEFAULT NULL
#define GlobalStatistics_search_statistics_MSGTYPE DetailedSearchStatistic

#define IpAddressMask_FIELDLIST(X, a_) \
X(a_, STATIC,   OPTIONAL, UINT32,   a,                 1) \
X(a_, STATIC,   OPTIONAL, UINT32,   b,                 2) \
X(a_, STATIC,   OPTIONAL, UINT32,   c,                 3) \
X(a_, STATIC,   OPTIONAL, UINT32,   d,                 4) \
X(a_, STATIC,   OPTIONAL, UINT32,   bits,              5) \
X(a_, STATIC,   OPTIONAL, UINT32,   token,             6)
#define IpAddressMask_CALLBACK NULL
#define IpAddressMask_DEFAULT NULL

#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    matchmaking,       1) \
X(a, CALLBACK, REPEATED, UINT32,   waiting_account_id_sessions,   2) \
X(a, CALLBACK, OPTIONAL, STRING,   error,             3) \
X(a, CALLBACK, REPEATED, UINT32,   ongoingmatch_account_id_sessions,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  global_stats,      7) \
X(a, CALLBACK, REPEATED, UINT32,   failping_account_id_sessions,   8) \
X(a, CALLBACK, REPEATED, UINT32,   penalty_account_id_sessions,   9) \
X(a, CALLBACK, REPEATED, UINT32,   failready_account_id_sessions,  10) \
X(a, CALLBACK, REPEATED, UINT32,   vacbanned_account_id_sessions,  11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  server_ipaddress_mask,  12) \
X(a, CALLBACK, REPEATED, MESSAGE,  notes,            13) \
X(a, CALLBACK, REPEATED, UINT32,   penalty_account_id_sessions_green,  14) \
X(a, CALLBACK, REPEATED, UINT32,   insufficientlevel_sessions,  15) \
X(a, CALLBACK, REPEATED, UINT32,   vsncheck_account_id_sessions,  16) \
X(a, CALLBACK, REPEATED, UINT32,   launcher_mismatch_sessions,  17) \
X(a, CALLBACK, REPEATED, UINT32,   insecure_account_id_sessions,  18)
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_CALLBACK pb_default_field_callback
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_DEFAULT NULL
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_global_stats_MSGTYPE GlobalStatistics
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_server_ipaddress_mask_MSGTYPE IpAddressMask
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_notes_MSGTYPE CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note

#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    type,              1) \
X(a, STATIC,   OPTIONAL, INT32,    region_id,         2) \
X(a, STATIC,   OPTIONAL, FLOAT,    region_r,          3) \
X(a, STATIC,   OPTIONAL, FLOAT,    distance,          4)
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_CALLBACK NULL
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_DEFAULT NULL

extern const pb_msgdesc_t CMsgGCCStrike15_v2_Party_Search_msg;
extern const pb_msgdesc_t CMsgGCCStrike15_v2_Party_SearchResults_msg;
extern const pb_msgdesc_t CMsgGCCStrike15_v2_Party_SearchResults_Entry_msg;
extern const pb_msgdesc_t CMsgGCCStrike15_v2_Party_Invite_msg;
extern const pb_msgdesc_t DetailedSearchStatistic_msg;
extern const pb_msgdesc_t GlobalStatistics_msg;
extern const pb_msgdesc_t IpAddressMask_msg;
extern const pb_msgdesc_t CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_msg;
extern const pb_msgdesc_t CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CMsgGCCStrike15_v2_Party_Search_fields &CMsgGCCStrike15_v2_Party_Search_msg
#define CMsgGCCStrike15_v2_Party_SearchResults_fields &CMsgGCCStrike15_v2_Party_SearchResults_msg
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_fields &CMsgGCCStrike15_v2_Party_SearchResults_Entry_msg
#define CMsgGCCStrike15_v2_Party_Invite_fields &CMsgGCCStrike15_v2_Party_Invite_msg
#define DetailedSearchStatistic_fields &DetailedSearchStatistic_msg
#define GlobalStatistics_fields &GlobalStatistics_msg
#define IpAddressMask_fields &IpAddressMask_msg
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_fields &CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_msg
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_fields &CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_msg

/* Maximum encoded size of messages (where known) */
/* CMsgGCCStrike15_v2_Party_Search_size depends on runtime parameters */
/* CMsgGCCStrike15_v2_Party_SearchResults_size depends on runtime parameters */
/* GlobalStatistics_size depends on runtime parameters */
/* CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_size depends on runtime parameters */
#define CMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate_Note_size 32
#define CMsgGCCStrike15_v2_Party_Invite_size     12
#define CMsgGCCStrike15_v2_Party_SearchResults_Entry_size 36
#define DetailedSearchStatistic_size             18
#define IpAddressMask_size                       36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
