name: MSBuild

on:
  push:

env:
  SOLUTION_FILE_PATH: NezuLoader.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]
    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.BUILD_CONFIGURATION}}
        path: NezuLoader/${{matrix.BUILD_CONFIGURATION}}/*.*
